/**
 * Mock data for content: Proposal, Videos, Documents
 */

import type { Proposal, Video, Document } from "@/types";

// Date helpers
const now = new Date();
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

// Mock Proposal
export const mockProposal: Proposal = {
  id: "proposal-1",
  hubId: "hub-1",
  fileName: "AgentFlow_Proposal_WhitmoreAssociates.pptx",
  fileSize: 15728640,
  mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  uploadedAt: daysAgo(14),
  uploadedBy: "user-staff-1",
  totalSlides: 24,
  embedUrl: "https://view.officeapps.live.com/op/embed.aspx?src=...",
  downloadUrl: "https://storage.agentflow.com/proposals/proposal-1.pptx",
  thumbnailUrl: "https://storage.agentflow.com/thumbnails/proposal-1.png",
  settings: {
    isClientVisible: true,
    isDownloadEnabled: true,
  },
  versions: [
    { version: 2, uploadedAt: daysAgo(7), uploadedBy: "user-staff-1", uploadedByName: "Hamish Nicklin", fileName: "AgentFlow_Proposal_v2.pptx" },
    { version: 1, uploadedAt: daysAgo(14), uploadedBy: "user-staff-1", uploadedByName: "Hamish Nicklin", fileName: "AgentFlow_Proposal_v1.pptx" },
  ],
};

// Mock Videos
export const mockVideos: Video[] = [
  {
    id: "video-1",
    hubId: "hub-1",
    title: "Welcome from the Team",
    description: "A personal introduction from our team leads",
    sourceType: "upload",
    sourceUrl: "https://storage.agentflow.com/videos/video-1.mp4",
    thumbnailUrl: "https://storage.agentflow.com/thumbnails/video-1.png",
    duration: 180,
    visibility: "client",
    uploadedAt: daysAgo(14),
    uploadedBy: "user-staff-1",
    uploadedByName: "Hamish Nicklin",
    views: 8,
    avgWatchTime: 165,
  },
  {
    id: "video-2",
    hubId: "hub-1",
    title: "Platform Demo",
    description: "Walkthrough of key platform features",
    sourceType: "link",
    sourceUrl: "https://www.youtube.com/watch?v=example",
    thumbnailUrl: null,
    duration: 420,
    visibility: "client",
    uploadedAt: daysAgo(10),
    uploadedBy: "user-staff-1",
    uploadedByName: "Hamish Nicklin",
    views: 5,
    avgWatchTime: 380,
  },
];

// Mock Documents
export const mockDocuments: Document[] = [
  // Pitch Hub (hub-1) documents
  {
    id: "doc-1",
    hubId: "hub-1",
    name: "Case Study - TechStart",
    description: "How we helped TechStart increase engagement by 40%",
    fileName: "CaseStudy_TechStart.pdf",
    fileSize: 2097152,
    mimeType: "application/pdf",
    category: "reference",
    visibility: "client",
    uploadedAt: daysAgo(12),
    uploadedBy: "user-staff-1",
    uploadedByName: "Hamish Nicklin",
    downloadUrl: "https://storage.agentflow.com/docs/doc-1.pdf",
    embedUrl: "https://view.officeapps.live.com/op/embed.aspx?src=...",
    views: 3,
    downloads: 2,
    versions: [],
  },
  {
    id: "doc-2",
    hubId: "hub-1",
    name: "Pricing Breakdown",
    description: "Detailed pricing for all service tiers",
    fileName: "Pricing_2024.xlsx",
    fileSize: 524288,
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    category: "contract",
    visibility: "client",
    uploadedAt: daysAgo(8),
    uploadedBy: "user-staff-1",
    uploadedByName: "Hamish Nicklin",
    downloadUrl: "https://storage.agentflow.com/docs/doc-2.xlsx",
    embedUrl: "https://view.officeapps.live.com/op/embed.aspx?src=...",
    views: 6,
    downloads: 4,
    versions: [],
  },
  {
    id: "doc-3",
    hubId: "hub-1",
    name: "Internal Brief Notes",
    description: "Discovery call notes and requirements",
    fileName: "Brief_Notes.docx",
    fileSize: 102400,
    mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    category: "brief",
    visibility: "internal",
    uploadedAt: daysAgo(28),
    uploadedBy: "user-staff-1",
    uploadedByName: "Hamish Nicklin",
    downloadUrl: "https://storage.agentflow.com/docs/doc-3.docx",
    embedUrl: "https://view.officeapps.live.com/op/embed.aspx?src=...",
    views: 2,
    downloads: 1,
    versions: [],
  },

  // Client Hub (hub-3 - Meridian Digital) documents
  {
    id: "doc-meridian-1",
    hubId: "hub-3",
    name: "Signed Master Services Agreement",
    description: "Executed MSA between AgentFlow and Meridian Digital",
    fileName: "Meridian_Digital_MSA_Signed.pdf",
    fileSize: 1048576,
    mimeType: "application/pdf",
    category: "contract",
    visibility: "client",
    uploadedAt: daysAgo(45),
    uploadedBy: "user-staff-1",
    uploadedByName: "Hamish Nicklin",
    downloadUrl: "https://storage.agentflow.com/docs/doc-meridian-1.pdf",
    embedUrl: "https://view.officeapps.live.com/op/embed.aspx?src=...",
    views: 12,
    downloads: 3,
    versions: [],
  },
  {
    id: "doc-meridian-2",
    hubId: "hub-3",
    name: "Website Redesign - Scope of Work",
    description: "Detailed scope, deliverables, and timeline for the website redesign project",
    fileName: "Meridian_Website_SOW_v2.pdf",
    fileSize: 2621440,
    mimeType: "application/pdf",
    category: "brief",
    visibility: "client",
    uploadedAt: daysAgo(42),
    uploadedBy: "user-staff-1",
    uploadedByName: "Hamish Nicklin",
    downloadUrl: "https://storage.agentflow.com/docs/doc-meridian-2.pdf",
    embedUrl: "https://view.officeapps.live.com/op/embed.aspx?src=...",
    views: 8,
    downloads: 5,
    versions: [
      { version: 2, uploadedAt: daysAgo(42), uploadedBy: "user-staff-1", uploadedByName: "Hamish Nicklin", fileName: "Meridian_Website_SOW_v2.pdf" },
      { version: 1, uploadedAt: daysAgo(48), uploadedBy: "user-staff-1", uploadedByName: "Hamish Nicklin", fileName: "Meridian_Website_SOW_v1.pdf" },
    ],
  },
  {
    id: "doc-meridian-3",
    hubId: "hub-3",
    name: "Q1 Campaign - Scope of Work",
    description: "Scope and deliverables for the Q1 marketing campaign",
    fileName: "Meridian_Q1Campaign_SOW.pdf",
    fileSize: 1572864,
    mimeType: "application/pdf",
    category: "brief",
    visibility: "client",
    uploadedAt: daysAgo(21),
    uploadedBy: "user-staff-1",
    uploadedByName: "Hamish Nicklin",
    downloadUrl: "https://storage.agentflow.com/docs/doc-meridian-3.pdf",
    embedUrl: "https://view.officeapps.live.com/op/embed.aspx?src=...",
    views: 5,
    downloads: 2,
    versions: [],
  },
  {
    id: "doc-meridian-4",
    hubId: "hub-3",
    name: "NDA - Mutual Non-Disclosure Agreement",
    description: "Signed mutual NDA protecting confidential information",
    fileName: "Meridian_NDA_Executed.pdf",
    fileSize: 524288,
    mimeType: "application/pdf",
    category: "contract",
    visibility: "client",
    uploadedAt: daysAgo(60),
    uploadedBy: "user-staff-1",
    uploadedByName: "Hamish Nicklin",
    downloadUrl: "https://storage.agentflow.com/docs/doc-meridian-4.pdf",
    embedUrl: "https://view.officeapps.live.com/op/embed.aspx?src=...",
    views: 4,
    downloads: 1,
    versions: [],
  },
  {
    id: "doc-meridian-5",
    hubId: "hub-3",
    name: "Brand Guidelines - Meridian Digital",
    description: "Client brand assets, colours, typography, and usage guidelines",
    fileName: "Meridian_Brand_Guidelines.pdf",
    fileSize: 8388608,
    mimeType: "application/pdf",
    category: "reference",
    visibility: "client",
    uploadedAt: daysAgo(40),
    uploadedBy: "user-staff-1",
    uploadedByName: "Hamish Nicklin",
    downloadUrl: "https://storage.agentflow.com/docs/doc-meridian-5.pdf",
    embedUrl: "https://view.officeapps.live.com/op/embed.aspx?src=...",
    views: 15,
    downloads: 8,
    versions: [],
  },
  {
    id: "doc-meridian-6",
    hubId: "hub-3",
    name: "Homepage Hero Design Options",
    description: "Three design concepts for homepage hero section - requires client approval",
    fileName: "Homepage_Hero_Options_v3.pdf",
    fileSize: 15728640,
    mimeType: "application/pdf",
    category: "deliverable",
    visibility: "client",
    uploadedAt: daysAgo(2),
    uploadedBy: "user-staff-1",
    uploadedByName: "Hamish Nicklin",
    downloadUrl: "https://storage.agentflow.com/docs/doc-meridian-6.pdf",
    embedUrl: "https://view.officeapps.live.com/op/embed.aspx?src=...",
    views: 3,
    downloads: 1,
    versions: [
      { version: 3, uploadedAt: daysAgo(2), uploadedBy: "user-staff-1", uploadedByName: "Hamish Nicklin", fileName: "Homepage_Hero_Options_v3.pdf" },
      { version: 2, uploadedAt: daysAgo(5), uploadedBy: "user-staff-1", uploadedByName: "Hamish Nicklin", fileName: "Homepage_Hero_Options_v2.pdf" },
      { version: 1, uploadedAt: daysAgo(10), uploadedBy: "user-staff-1", uploadedByName: "Hamish Nicklin", fileName: "Homepage_Hero_Options_v1.pdf" },
    ],
  },
  {
    id: "doc-meridian-7",
    hubId: "hub-3",
    name: "Monthly Status Report - November",
    description: "Project progress, hours used, and upcoming milestones",
    fileName: "Meridian_Status_Report_Nov2025.pdf",
    fileSize: 1048576,
    mimeType: "application/pdf",
    category: "deliverable",
    visibility: "client",
    uploadedAt: daysAgo(3),
    uploadedBy: "user-staff-1",
    uploadedByName: "Hamish Nicklin",
    downloadUrl: "https://storage.agentflow.com/docs/doc-meridian-7.pdf",
    embedUrl: "https://view.officeapps.live.com/op/embed.aspx?src=...",
    views: 2,
    downloads: 1,
    versions: [],
  },
  {
    id: "doc-meridian-8",
    hubId: "hub-3",
    name: "Discovery Session Notes",
    description: "Key findings from initial discovery workshops",
    fileName: "Meridian_Discovery_Notes.pdf",
    fileSize: 786432,
    mimeType: "application/pdf",
    category: "brief",
    visibility: "client",
    uploadedAt: daysAgo(44),
    uploadedBy: "user-staff-1",
    uploadedByName: "Hamish Nicklin",
    downloadUrl: "https://storage.agentflow.com/docs/doc-meridian-8.pdf",
    embedUrl: "https://view.officeapps.live.com/op/embed.aspx?src=...",
    views: 6,
    downloads: 2,
    versions: [],
  },
];
